#!/usr/bin/env python
# simple command line script to remove files and folders copied to the wrong spot

import os, sys, getopt
from send2trash import send2trash

def main(argv):
	source_dir = ''# /path/to/source the folder you copied the files from
	target_dir = ''# /path/to dest the folder you copied the files to
	debug = True

	# get arguments
	try:
		opts, args = getopt.getopt(argv,"hs:t:",["source=","target="])
	except getopt.GetoptError:
		print 'usage: reverse -s <source_dir> -t <target_dir>'
		sys.exit(2)

	# Set aruments accordingly
	for opt, arg in opts:
		if opt == '-h':
			print 'usage: reverse -s <source> -t <target> \nsource: the folder you copied the files from\ntarget: the folder you copied to'
			sys.exit()
		elif opt in ("-s", "--source"):
			source_dir = arg
		elif opt in ("-t", "--target"):
			target_dir = arg

	for root, dirs, files in os.walk(source_dir, topdown=False):
		for name in files:
			try:
				send2trash(os.path.join(target_dir, name))
			except:
				pass
				for name in dirs:
					try:
						send2trash(os.path.join(target_dir, name))
					except:
						pass
if __name__ == "__main__":
	main(sys.argv[1:])